package com.voidsow.community.backend.mapper;

import com.voidsow.community.backend.entity.Chat;
import com.voidsow.community.backend.entity.ChatExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

@Mapper
public interface ChatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    long countByExample(ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    int deleteByExample(ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    int insert(Chat row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    int insertSelective(Chat row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    List<Chat> selectByExampleWithRowbounds(ChatExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    List<Chat> selectByExample(ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    Chat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    int updateByExampleSelective(@Param("row") Chat row, @Param("example") ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    int updateByExample(@Param("row") Chat row, @Param("example") ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    int updateByPrimaryKeySelective(Chat row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    int updateByPrimaryKey(Chat row);
}