server:
  servlet:
    context-path: /
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://
    username:
    password:
  sql:
    init:
      data-locations: classpath:sql/*.sql
      mode: always
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          ssl:
            enable: true
  redis:
    host:
    database: 1
    password:
  rabbitmq:
    host:
    username: admin
    password: 123456
    listener:
      direct:
        acknowledge-mode: none
  elasticsearch:


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.voidsow.community.backend.entity


logging:
  level:
    com:
      voidsow:
        community:
          backend:

test:
  mail:
    to:

community:
  # 社区名
  brand: Café Stella
  # 前端
  domain: localhost:8080
  backend: localhost:8081
  path:
  # 文件上传路径
    upload:
  # 分页配置
  page:
    # 页大小
    size: 5
    # 页数量
    num: 5
  token:
    # token的有效时间，单位为秒
    duration:
      # 会话级
      session: 1800
      # 长期有效时间
      long-term: 2592000 #30*24*3600