package com.voidsow.community.backend.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.Date;

@JsonIgnoreProperties({"id", "conversationId", "status"})
public class Chat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.id
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.speaker
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    private Integer speaker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.listener
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    private Integer listener;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.conversation_id
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    private String conversationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.content
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.status
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.gmt_create
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    private Date gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    public Chat(Integer id, Integer speaker, Integer listener, String conversationId, String content, Integer status, Date gmtCreate) {
        this.id = id;
        this.speaker = speaker;
        this.listener = listener;
        this.conversationId = conversationId;
        this.content = content;
        this.status = status;
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    public Chat() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.id
     *
     * @return the value of chat.id
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.id
     *
     * @param id the value for chat.id
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.speaker
     *
     * @return the value of chat.speaker
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    public Integer getSpeaker() {
        return speaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.speaker
     *
     * @param speaker the value for chat.speaker
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    public void setSpeaker(Integer speaker) {
        this.speaker = speaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.listener
     *
     * @return the value of chat.listener
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    public Integer getListener() {
        return listener;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.listener
     *
     * @param listener the value for chat.listener
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    public void setListener(Integer listener) {
        this.listener = listener;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.conversation_id
     *
     * @return the value of chat.conversation_id
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    public String getConversationId() {
        return conversationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.conversation_id
     *
     * @param conversationId the value for chat.conversation_id
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    public void setConversationId(String conversationId) {
        this.conversationId = conversationId == null ? null : conversationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.content
     *
     * @return the value of chat.content
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.content
     *
     * @param content the value for chat.content
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.status
     *
     * @return the value of chat.status
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.status
     *
     * @param status the value for chat.status
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.gmt_create
     *
     * @return the value of chat.gmt_create
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.gmt_create
     *
     * @param gmtCreate the value for chat.gmt_create
     * @mbg.generated Sun May 08 14:09:40 CST 2022
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}