package com.voidsow.community.backend.entity;

import java.util.Date;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.id
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.uid
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.title
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.type
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.status
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.gmt_create
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.gmt_modified
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.comment_num
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    private Integer commentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.score
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.content
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public Post(Integer id, Integer uid, String title, Integer type, Integer status, Date gmtCreate, Date gmtModified, Integer commentNum, Double score) {
        this.id = id;
        this.uid = uid;
        this.title = title;
        this.type = type;
        this.status = status;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
        this.commentNum = commentNum;
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public Post(Integer id, Integer uid, String title, Integer type, Integer status, Date gmtCreate, Date gmtModified, Integer commentNum, Double score, String content) {
        this.id = id;
        this.uid = uid;
        this.title = title;
        this.type = type;
        this.status = status;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
        this.commentNum = commentNum;
        this.score = score;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public Post() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.id
     *
     * @return the value of post.id
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.id
     *
     * @param id the value for post.id
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.uid
     *
     * @return the value of post.uid
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.uid
     *
     * @param uid the value for post.uid
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.title
     *
     * @return the value of post.title
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.title
     *
     * @param title the value for post.title
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.type
     *
     * @return the value of post.type
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.type
     *
     * @param type the value for post.type
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.status
     *
     * @return the value of post.status
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.status
     *
     * @param status the value for post.status
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.gmt_create
     *
     * @return the value of post.gmt_create
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.gmt_create
     *
     * @param gmtCreate the value for post.gmt_create
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.gmt_modified
     *
     * @return the value of post.gmt_modified
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.gmt_modified
     *
     * @param gmtModified the value for post.gmt_modified
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.comment_num
     *
     * @return the value of post.comment_num
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public Integer getCommentNum() {
        return commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.comment_num
     *
     * @param commentNum the value for post.comment_num
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public void setCommentNum(Integer commentNum) {
        this.commentNum = commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.score
     *
     * @return the value of post.score
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.score
     *
     * @param score the value for post.score
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.content
     *
     * @return the value of post.content
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.content
     *
     * @param content the value for post.content
     *
     * @mbg.generated Tue Apr 26 20:33:20 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}